// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAaBaJhkgjrG07m6sjg5E7ORsyR16NQNNo',
    appId: '1:861062944941:web:2611993ceccfd814a20e24',
    messagingSenderId: '861062944941',
    projectId: 'mozz-chat-project',
    authDomain: 'mozz-chat-project.firebaseapp.com',
    databaseURL: 'https://mozz-chat-project-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'mozz-chat-project.appspot.com',
    measurementId: 'G-VL0XR4VDSK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDhHf8Ik-zeYHvfh-KH262TpC0TO-pCQQg',
    appId: '1:861062944941:android:b7ee6291e288b93ca20e24',
    messagingSenderId: '861062944941',
    projectId: 'mozz-chat-project',
    databaseURL: 'https://mozz-chat-project-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'mozz-chat-project.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAcAQ2sl1MN17F5BJe6Arr6UNjiDN64E3w',
    appId: '1:861062944941:ios:935b2319e90c797ba20e24',
    messagingSenderId: '861062944941',
    projectId: 'mozz-chat-project',
    databaseURL: 'https://mozz-chat-project-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'mozz-chat-project.appspot.com',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAcAQ2sl1MN17F5BJe6Arr6UNjiDN64E3w',
    appId: '1:861062944941:ios:1a4dcabdd6952969a20e24',
    messagingSenderId: '861062944941',
    projectId: 'mozz-chat-project',
    databaseURL: 'https://mozz-chat-project-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'mozz-chat-project.appspot.com',
    iosBundleId: 'com.example.chatApp.RunnerTests',
  );
}
